import React, { useState } from 'react';
import { ProcessedFile, FileStatus } from '../types';

interface MarkdownPreviewProps {
  file: ProcessedFile | undefined;
}

const MarkdownPreview: React.FC<MarkdownPreviewProps> = ({ file }) => {
  const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle');

  const handleCopy = () => {
    if (file?.markdown) {
      navigator.clipboard.writeText(file.markdown);
      setCopyState('copied');
      setTimeout(() => setCopyState('idle'), 2000);
    }
  };

  const handleDownload = () => {
    if (file?.markdown) {
      const blob = new Blob([file.markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${file.originalName.replace(/\.[^/.]+$/, "")}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  if (!file) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-gray-400 bg-white rounded-xl border-2 border-dashed border-gray-200">
        <i className="ph ph-eye-slash text-4xl mb-3 opacity-30"></i>
        <p>Select a file to preview generated markdown</p>
      </div>
    );
  }

  if (file.status === FileStatus.ERROR) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-red-500 bg-red-50 rounded-xl border border-red-200 p-8 text-center">
        <i className="ph ph-warning-octagon text-5xl mb-4"></i>
        <h3 className="text-lg font-semibold mb-2">Processing Failed</h3>
        <p className="text-sm opacity-80">{file.error || "An unknown error occurred while processing this file."}</p>
      </div>
    );
  }

  if (file.status !== FileStatus.COMPLETED) {
     return (
      <div className="h-full flex flex-col items-center justify-center text-indigo-500 bg-white rounded-xl border border-gray-200 p-8 text-center">
        <i className="ph ph-cpu animate-pulse text-5xl mb-4"></i>
        <h3 className="text-lg font-semibold mb-2 text-gray-800">AI is Analyzing</h3>
        <p className="text-sm text-gray-500 animate-pulse">Extracting text and structuring markdown...</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-white rounded-xl border border-gray-200 overflow-hidden shadow-lg">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 bg-gray-50 border-b border-gray-200">
        <div className="flex items-center gap-2 text-sm text-gray-600">
          <i className="ph ph-markdown-logo text-lg text-indigo-600"></i>
          <span className="font-mono font-medium">{file.originalName}.md</span>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 rounded-lg transition-colors shadow-sm"
          >
            {copyState === 'copied' ? (
              <>
                <i className="ph ph-check text-green-500"></i> Copied
              </>
            ) : (
              <>
                <i className="ph ph-copy"></i> Copy
              </>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors shadow-lg shadow-indigo-500/20"
          >
            <i className="ph ph-download-simple"></i> Download
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto custom-scrollbar p-6 bg-white">
        <pre className="font-mono text-sm text-gray-800 whitespace-pre-wrap leading-relaxed max-w-none">
          {file.markdown}
        </pre>
      </div>
      
      {/* Footer / Stats */}
      <div className="px-4 py-2 bg-gray-50 border-t border-gray-200 text-xs text-gray-500 flex justify-between">
        <span>Generated by Gemini 2.5 Flash</span>
        <span>{file.markdown.length} characters</span>
      </div>
    </div>
  );
};

export default MarkdownPreview;